### ISSUE TITLE
the extention does nothing

### ISSUE THREAD

**Issue by nigelmcdonald** [matt0x5B/HideYoutubeWatchedVideos-Issues#3]
**Describe the bug**
Install the extension, reload YouTube and all still see tons of watched videos (at https://www.youtube.com). I have tried toggling the extension eye icon to both red and yellow and they both have no effect on reloading watched videos.

**Expected behavior**
not see watched videos in my feed

**Screenshots**
N/A, seeing a picture of what i describe as a watched video doesn't seem prudent here

**Browser (please complete the following information):**
 - Browser: Opera GX
 - Version LVL3 (core: 85.0.4341.72)

**Comment by matt0x5B** [comment]
Thank you for submitting this information, I will work on reproducing this issue and hopefully get it resolved for you.

Due to the method in which the extension detects which videos have been watched, the information that would be shown within a screenshot can be helpful to me in diagnosing the issue. However I understand if you are not comfortable in submitting a screenshot containing watch history.

**Comment by matt0x5B** [comment]
@nigelmcdonald I have been unable to reproduce this bug, could you please confirm if this issue still exists and if it is, could you please provide more information, such as a screenshot of the YouTube layout that you see.

I you are unable to provide anymore information I will have to mark this bug report as closed. Thanks.
